optimizer: {
  type: AdamW,
  kwargs: {
    lr: 0.0005,
    weight_decay: 0.05
  }}

scheduler: {
  type: CosLR,
  kwargs: {
    epochs: 300,
    initial_epochs: 10
}}

dataset: {
  train: { _base_: cfgs/dataset_configs/ShapeNet-55.yaml,
            others: {subset: 'train', npoints: 1024}},
  val: { _base_: cfgs/dataset_configs/ShapeNet-55.yaml,
            others: {subset: 'test', npoints: 1024}},
  test: { _base_: cfgs/dataset_configs/ShapeNet-55.yaml,
            others: {subset: 'test', npoints: 1024}}}

model: {
  NAME: Point_MaDi,
  group_size: 32,
  num_group: 64,
  loss: cdl2,
  gamma: 0.1,
  encoder_config: {
    mask_ratio_rand: 0.6,
    mask_ratio_block: 0.6,
    trans_dim: 384,
    encoder_dims: 384,
    depth: 12,
    drop_path_rate: 0.1,
    num_heads: 6,
  },
  diffusion_config: {
    num_steps: 2000,
    beta_start: 0.0001,
    beta_end: 0.02,
    use_time: False,
  },
  decoder_config: {
    depth: 4,
    drop_path_rate: 0.1,
    num_heads: 6,
  },
  }

npoints: 1024
total_bs: 128
step_per_update: 1
max_epoch: 300